### ISSUE TITLE
Helmrelease (v 3.4.8) can't start on 64MB of memory 

### ISSUE THREAD

**Issue by dzikoysk** [reposilite-playground/reposilite-helm#13]
Moved from `dzikoysk/reposilite`:

* https://github.com/dzikoysk/reposilite/issues/1933

**Comment by dzikoysk** [comment]
By the way, may I ask what's your limits @justusbunsi? Joshua runs it on K3 and default limits seems to work fine for him, so it'd be nice to gather a little bit more feedback on that.

**Comment by SirEndii** [comment]
I was able to reproduce this with a fresh k3s cluster installation
Fixed it by increasing the resource limits to a higher value

**Comment by dzikoysk** [comment]
Ok, I've increased default limits to these values:

https://github.com/reposilite-playground/reposilite-helm/blob/77a25f07cfe2d009d3802e3c4aa27d888544c0c3/charts/reposilite/values.yaml#L128-L139

I think it's ok to have even a little bit higher supply of resources by default, especially that we need to pay extra for this whole setup related to container itself & cloud. Anyone who would like to limit the usage to minimum can play individually on their own with these values.

**Comment by justusbunsi** [comment]
> By the way, may I ask what's your limits @justusbunsi? Joshua runs it on K3 and default limits seems to work fine for him, so it'd be nice to gather a little bit more feedback on that.

Sorry for not replying earlier. Looks like this issue has been resolved in the meantime but I still wanted to answer your question. Running on bare-metal Kubernetes (kubeadm) and have resources like these:

```yaml
resources:
  limits:
    cpu: null
    memory: 2048Mi
  requests:
    cpu: "0.1"
    memory: 2048Mi

env:
  - name: JAVA_OPTS
    value: "-Xms1000M -Xmx2000M -XX:+AlwaysPreTouch"
```

I had similar issues with the defaults and applied some over-the-top resources. 😄 I can probably decrease the values.
