### ISSUE TITLE
service.yaml template does not properly support NodePort

### ISSUE THREAD

**Issue by rmpinchback** [reposilite-playground/reposilite-helm#14]
The service.yaml template contains:

```
spec:
  type: {{ .Values.service.type }}
```

which of course would allow for values.yaml to specify NodePort.  Unfortunately, the lines following don't allow for specifying a nodePort value.

I believe the template should be changed from:

```
apiVersion: v1
kind: Service
metadata:
  name: {{ include "reposilite.fullname" . }}
  annotations:
  {{- with .Values.service.annotations  }}
    {{ toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "reposilite.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "reposilite.selectorLabels" . | nindent 4 }}
```

to:

```
apiVersion: v1
kind: Service
metadata:
  name: {{ include "reposilite.fullname" . }}
  annotations:
  {{- with .Values.service.annotations  }}
    {{ toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "reposilite.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if (and (contains "NodePort" .Values.service.type) (not (empty .Values.service.nodePort))) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "reposilite.selectorLabels" . | nindent 4 }}
```
